language: python

git:
    depth: false
services:
    - docker
addons:
    ssh_known_hosts: github.ibm.com
deploy:
    - provider: script
      script: >-
          set -e; make docker-build-images docker-test-images docker-quality-images deploy
      on:
          all_branches: true
          # only build docker image and push once
          condition: $TOXENV = py38
          # only deploy when pushing to gh repo
          repo: IBM/detect-secrets
matrix:
    include:
        - env: TOXENV=py37
          python: 3.7.13
          dist: xenial # Required for Python >= 3.7 (travis-ci/travis-ci#9069), the GitHub Travis build will use Python 3.7.1 by default if you provide 3.7 without a patch version and the build will fail with AttributeError: 'str' object has no attribute 'name'
        - env: TOXENV=py38
          python: 3.8
          dist: xenial # Required for Python >= 3.7 (travis-ci/travis-ci#9069)
before_install:
    - echo -e "machine github.com\n  login $GH_ACCESS_TOKEN" >> ~/.netrc # Login to GitHub
    - echo -e "machine github.ibm.com\n  login $GHE_ACCESS_TOKEN" >> ~/.netrc # Login to GitHub Enterprise
install:    
    - pip install "certifi>=2022.12.07" "setuptools>=65.5.1" tox pipenv
script: make setup-trivy && make trivy-scan-python-vulnerabilities && make test
cache:
    directories:
        - $HOME/.cache/pre-commit
        - $HOME/.cache/trivy
