credentials:
    some_value_here: not_secret
    other_value_here: 1234567890a
    CanonicalUserGetSkippedByExcludeLines: 1234567890ab
    nested:
        value: AKIAabcdefghijklmnop
        other_value: abcdefghijklmnop
list_of_keys:
    - 123
    - 456
    - 234567890a

test_agent::allowlisted_api_key: 'ToCynx5Se4e2PtoZxEhW7lUJcOX15c54'  # pragma: allowlist secret

high_entropy_binary_secret: !!binary MjNjcnh1IDJieXJpdXYyeXJpaTJidnl1MnI4OXkyb3UwMg==
