name: pr

on: pull_request

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3
      - uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912  # v4
        with:
          python-version: 3.8
      - name: pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507  # v3

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3
      - uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912  # v4
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run Mypy
        run: |
          mypy

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3
    - uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912  # v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Sets env var for release
      if: ${{ matrix.os == 'macos-latest' && matrix.python == '3.7' }}
      run: |
        # NO_PROXY is needed to call requests API within a forked process
        # when using macOS and python version 3.7
        echo "NO_PROXY='*'" >> $GITHUB_ENV
    - name: Run tests
      run: pytest --strict-markers -W ignore::UserWarning tests
